dtype = {
'CO_IES': Numeric (8),
'NO_IES': String(200),
'CO_CATEGORIA_ADMINISTRATIVA': Numeric (8),
'DS_CATEGORIA_ADMINISTRATIVA': String(100),
'CO_ORGANIZACAO_ACADEMICA':  Numeric (8),
'DS_ORGANIZACAO_ACADEMICA': String(100),
'CO_MUNICIPIO_CURSO': Numeric (8),
'NO_MUNICIPIO_CURSO': String(200),
'CO_UF_CURSO': Numeric (8),
'SGL_UF_CURSO': String(2),
'NO_REGIAO_CURSO': String(30),
'IN_CAPITAL_CURSO': Numeric (8),
'CO_CURSO': Numeric (8),
'NO_CURSO': String(200),
'CO_SITUACAO_CURSO':  Numeric (10),
'DS_SITUACAO_CURSO': String(100),
'CO_OCDE':  String(12),
'NO_OCDE': String(120),
'CO_OCDE_AREA_GERAL': String(12),
'NO_OCDE_AREA_GERAL': String(120),
'CO_OCDE_AREA_ESPECIFICA': String(12),
'NO_OCDE_AREA_ESPECIFICA': String(120),
'CO_OCDE_AREA_DETALHADA': String(12),
'NO_OCDE_AREA_DETALHADA': String(120),
'CO_GRAU_ACADEMICO': Numeric (8),
'DS_GRAU_ACADEMICO': String(100),
'CO_MODALIDADE_ENSINO': Numeric (8),
'DS_MODALIDADE_ENSINO': String(100),
'CO_NIVEL_ACADEMICO': Numeric (8),
'DS_NIVEL_ACADEMICO': String(100),
'IN_GRATUITO': Numeric (8),
'TP_ATRIBUTO_INGRESSO':Numeric (8),
'CO_LOCAL_OFERTA':Numeric (8),
'NU_CARGA_HORARIA':Numeric (8),
'DT_INICIO_FUNCIONAMENTO':Numeric (8),
'IN_AJUDA_DEFICIENTE':Numeric (8),
'IN_MATERIAL_DIGITAL':Numeric (8),
'IN_MATERIAL_TATIL':Numeric (8),
'IN_MATERIAL_IMPRESSO':Numeric (8),
'IN_MATERIAL_AUDIO':Numeric (8),
'IN_MATERIAL_BRAILLE':Numeric (8),
'IN_DISCIPLINA_LIBRAS':Numeric (8),
'IN_GUIA_INTERPRETE':Numeric (8),
'IN_MATERIAL_LIBRAS':Numeric (8),
'IN_RECURSOS_COMUNICACAO':Numeric (8),
'IN_RECURSOS_INFORMATICA':Numeric (8),
'IN_TRADUTOR_LIBRAS':Numeric (8),
'IN_INTEGRAL_CURSO':Numeric (8),
'IN_MATUTINO_CURSO':Numeric (8),
'IN_NOTURNO_CURSO':Numeric (8),
'IN_VESPERTINO_CURSO':Numeric (8),
'NU_INTEGRALIZACAO_MATUTINO':Numeric (8),
'NU_INTEGRALIZACAO_VESPERTINO':Numeric (8),
'NU_INTEGRALIZACAO_NOTURNO':Numeric (8),
'NU_INTEGRALIZACAO_INTEGRAL':Numeric (8),
'NU_INTEGRALIZACAO_EAD':Numeric (8),
'IN_OFERECE_DISC_SEMI_PRES':Numeric (8),
'NU_PERC_CAR_HOR_SEMI_PRES':Numeric (8),
'IN_POSSUI_LABORATORIO':Numeric (8),
'QT_INSCRITOS_PRINCIPAL_EAD':Numeric (8),
'QT_VAGAS_PRINCIPAL_EAD':Numeric (8),
'QT_VAGAS_PRINCIPAL_INTEGRAL':Numeric (8),
'QT_VAGAS_PRINCIPAL_MATUTINO':Numeric (8),
'QT_VAGAS_PRINCIPAL_NOTURNO':Numeric (8),
'QT_VAGAS_PRINCIPAL_VESPERTINO':Numeric (8),
'QT_INSCRITOS_PRINCIPAL_MATU':Numeric (8),
'QT_INSCRITOS_PRINCIPAL_VESP':Numeric (8),
'QT_INSCRITOS_PRINCIPAL_NOTURNO':Numeric (8),
'QT_INSCRITOS_PRINCIPAL_INTE':Numeric (8),
'QT_INSCRITOS_OUTRAS_VAGAS_EAD':Numeric (8),
'QT_OUTRAS_VAGAS_EAD':Numeric (8),
'QT_OUTRAS_VAGAS_INTEGRAL':Numeric (8),
'QT_OUTRAS_VAGAS_MATUTINO':Numeric (8),
'QT_OUTRAS_VAGAS_NOTURNO':Numeric (8),
'QT_OUTRAS_VAGAS_VESPERTINO':Numeric (8),
'QT_INSCRITOS_OUTRAS_VAGAS_MATU':Numeric (8),
'QT_INSCRITOS_OUTRAS_VAGAS_VESP':Numeric (8),
'QT_INSCRITOS_OUTRAS_VAGAS_NOT':Numeric (8),
'QT_INSCRITOS_OUTRAS_VAGAS_INTE':Numeric (8),
'QT_MATRICULA_CURSO':Numeric (8),
'QT_CONCLUINTE_CURSO':Numeric (8),
'QT_INGRESSO_CURSO':Numeric (8),
'QT_INGRESSO_PROCESSO_SELETIVO': Numeric (8)
}


















































