dtype = {
'CO_IES': numeric(8),
'CO_CATEGORIA_ADMINISTRATIVA': numeric(8),
'DS_CATEGORIA_ADMINISTRATIVA': String(50),
'CO_ORGANIZACAO_ACADEMICA': numeric(8),
'DS_ORGANIZACAO_ACADEMICA': String(100),
'CO_MUNICIPIO': numeric(8),
'CO_UF': numeric(8),
'CO_CURSO': numeric (8),
'NO_CURSO': String(200),
'CO_OCDE': String(12),
'NO_OCDE': String(120),
'CO_OCDE_AREA_GERAL': numeric(8),
'NO_AREA_GERAL': String(120),
'CO_OCDE_AREA_ESPECIFICA': numeric(8),
'NO_AREA_ESPECIFICA': String(120),
'CO_OCDE_AREA_DETALHADA': numeric(8),
'NO_AREA_DETALHADA': String(120),
'CO_GRAU_ACADEMICO': numeric(8),
'CO_MODALIDADE_ENSINO': numeric(8),
'CO_NIVEL_ACADEMICO': numeric(8),
'IN_GRATUITO': numeric(8),
'TP_ATRIBUTO_INGRESSO': numeric(8),
'CO_LOCAL_OFERTA_IES':  numeric(8),
'CO_MUNICIPIO':  numeric(8),
'CO_UF':  numeric(8),
'NU_CARGA_HORARIA': numeric (8) ,
'DT_INICIO_FUNCIONAMENTO': numeric (8) ,
'IN_AJUDA_DEFICIENTE': numeric (8) ,
'IN_MATERIAL_DIGITAL': numeric (8) ,
'IN_MATERIAL_IMPRESSO': numeric (8) ,
'IN_MATERIAL_AUDIO': numeric (8) ,
'IN_MATERIAL_BRAILLE': numeric (8) ,
'IN_DISCIPLINA_LIBRAS': numeric (8) ,
'IN_GUIA_INTERPRETE': numeric (8) ,
'IN_MATERIAL_LIBRAS': numeric (8) ,
'IN_SINTESE_VOZ': numeric (8) ,
'IN_TRADUTOR_LIBRAS': numeric (8) ,
'IN_INTEGRAL_CURSO': numeric (8) ,
'IN_MATUTINO_CURSO': numeric (8) ,
'IN_NOTURNO_CURSO': numeric (8) ,
'IN_VESPERTINO_CURSO': numeric (8) ,
'NU_PERC_CARGA_HOR_DISTANCIA': numeric (8) ,
'NU_INTEGRALIZACAO_MATUTINO': numeric (8) ,
'NU_INTEGRALIZACAO_VESPERTINO': numeric (8) ,
'NU_INTEGRALIZACAO_NOTURNO': numeric (8) ,
'NU_INTEGRALIZACAO_INTEGRAL': numeric (8) ,
'TP_MOTIVO_SEM_VINCULO': numeric (8) ,
'CO_CURSO_REPRESENTADO': numeric (8) ,
'IN_OFERECE_DISC_DISTANCIA': numeric (8) ,
'IN_UTILIZA_LABORATORIO': numeric (8) ,
'QT_INSCRITOS_ANO_EAD': numeric (8) ,
'QT_VAGAS_ANUAL_EAD': numeric (8) ,
'QT_VAGAS_INTEGRAL_PRES': numeric (8) ,
'QT_VAGAS_MATUTINO_PRES': numeric (8) ,
'QT_VAGAS_NOTURNO_PRES': numeric (8) ,
'QT_VAGAS_VESPERTINO_PRES': numeric (8) ,
'QT_INSCRITOS_MATUTINO_PRES': numeric (8) ,
'QT_INSCRITOS_VESPERTINO_PRES': numeric (8) ,
'QT_INSCRITOS_NOTURNO_PRES': numeric (8) ,
'QT_INSCRITOS_INTEGRAL_PRES': numeric (8) ,
'QT_MATRICULA_CURSO': numeric (8) ,
'QT_CONCLUINTE_CURSO': numeric (8) ,
'QT_INGRESSO_CURSO': numeric (8) ,
'QT_INGRESSO_PROCESSO_SELETIVO': numeric (8) ,
'QT_INGRESSO_OUTRA_FORMA': numeric (8) 
}







