CREATE TABLE IES_2009_VAGAS_INSCRITOS_EAD (
CO_IES numeric(8) NULL,
CO_CATEGORIA_ADMINISTRATIVA numeric(8) NULL,
DS_CATEGORIA_ADMINISTRATIVA char(50) NULL,
CO_ORGANIZACAO_ACADEMICA numeric(8) NULL,
NO_ORGANIZACAO_ACADEMICA char(100) NULL,
CO_CURSO numeric (8) NULL,
NO_CURSO char(200) NULL,
SGL_UF_IES char(2) NULL,
CO_CURSO_EAD numeric(8) NULL,
NO_CURSO_EAD char(200) NULL,
CO_GRAU_ACADEMICO numeric (8) NULL,
CO_NIVEL_ACADEMICO numeric (8) NULL,
CO_OCDE char(12) NULL,
NU_VAGAS_OFERECIDAS_EAD numeric (8) NULL,
QT_INSCRITOS_ANO_EAD numeric (8) NULL
);



