dtype = {
'CO_LOCAL_OFERTA_IES' : Numeric (8),
'CO_IES' : Numeric (8),
'CO_MUNICIPIO_LOCAL_OFERTA' : Numeric (8),
'NO_MUNICIPIO_LOCAL_OFERTA' : String (150),
'CO_UF_LOCAL_OFERTA' : Numeric (8),
'SGL_UF_LOCAL_OFERTA' : String (2),
'IN_SEDE' : Numeric (8),
'CO_CURSO_POLO' : Numeric (8),
'CO_CURSO' : Numeric (8),
'IN_LOCAL_OFERTA_NEAD' : Numeric (8),
'IN_LOCAL_OFERTA_UAB' : Numeric (8),
'IN_LOCAL_OFERTA_REITORIA' : Numeric (8),
'IN_LOCAL_OFERTA_POLO' : Numeric (8),
'IN_LOCAL_OFERTA_UNID_ACADEMICA' : Numeric (8),
}