CREATE TABLE COMTRADE_2000 (
	COD_PRODUTO char(4),
	DESC_PRODUTO char(200),
	COD_ESTIMACAO char(2),
	PESO_LIQUIDO numeric(15),
    CLASSIFICACAO char(3),
    ISO3_PARCEIRO char(5),
    COD_PARCEIRO char(3),
    DESC_PARCEIRO char(200),
    COD_QUANTIDADE char(3),
    DESC_QUANTIDADE char(100),
    COD_COMERCIO char(2),
    DESC_COMERCIO char(50),
    ISO3_REPORTER char(20),
    COD_REPORTER char(6),
    DESC_REPORTER char(50),
    QUANT_SUPLEMENTAR numeric(20),
    VALOR numeric(20),
    ANO numeric(4)
); 