use dataviva_raw;

drop table if exists IES_2013_CURSO;
create table IES_2013_CURSO(
CO_IES varchar(8),
NO_IES varchar(200),
CO_CATEGORIA_ADMINISTRATIVA varchar(8),
DS_CATEGORIA_ADMINISTRATIVA varchar(100),
CO_ORGANIZACAO_ACADEMICA varchar(8),
DS_ORGANIZACAO_ACADEMICA varchar(100),
CO_MUNICIPIO_CURSO varchar(8),
NO_MUNICIPIO_CURSO varchar(200),
CO_UF_CURSO varchar(8),
SGL_UF_CURSO varchar(2),
NO_REGIAO_CURSO varchar(30),
IN_CAPITAL_CURSO varchar(8),
CO_CURSO varchar(8),
NO_CURSO varchar(200),
CO_SITUACAO_CURSO varchar(10),
DS_SITUACAO_CURSO varchar(100),
CO_OCDE varchar(12),
NO_OCDE varchar(120),
CO_OCDE_AREA_GERAL varchar(5),
NO_OCDE_AREA_GERAL varchar(200),
CO_OCDE_AREA_ESPECIFICA varchar(5),
NO_OCDE_AREA_ESPECIFICA varchar(200),
CO_OCDE_AREA_DETALHADA varchar(5),
NO_OCDE_AREA_DETALHADA varchar(200),
CO_GRAU_ACADEMICO varchar(8),
DS_GRAU_ACADEMICO varchar(100),
CO_MODALIDADE_ENSINO varchar(8),
DS_MODALIDADE_ENSINO varchar(100),
CO_NIVEL_ACADEMICO varchar(8),
DS_NIVEL_ACADEMICO varchar(100),
IN_GRATUITO varchar(8),
TP_ATRIBUTO_INGRESSO varchar(8),
CO_LOCAL_OFERTA varchar(8),
NU_CARGA_HORARIA varchar(8),
DT_INICIO_FUNCIONAMENTO varchar(10),
IN_AJUDA_DEFICIENTE varchar(8),
IN_MATERIAL_DIGITAL varchar(8),
IN_MATERIAL_AMPLIADO varchar(8),
IN_MATERIAL_TATIL varchar(8),
IN_MATERIAL_IMPRESSO varchar(8),
IN_MATERIAL_AUDIO varchar(8),
IN_MATERIAL_BRAILLE varchar(8),
IN_DISCIPLINA_LIBRAS varchar(8),
IN_GUIA_INTERPRETE varchar(8),
IN_MATERIAL_LIBRAS varchar(8),
IN_RECURSOS_COMUNICACAO varchar(8),
IN_RECURSOS_INFORMATICA varchar(8),
IN_TRADUTOR_LIBRAS varchar(8),
IN_INTEGRAL_CURSO varchar(8),
IN_MATUTINO_CURSO varchar(8),
IN_NOTURNO_CURSO varchar(8),
IN_VESPERTINO_CURSO varchar(8),
NU_INTEGRALIZACAO_MATUTINO varchar(8),
NU_INTEGRALIZACAO_VESPERTINO varchar(8),
NU_INTEGRALIZACAO_NOTURNO varchar(8),
NU_INTEGRALIZACAO_INTEGRAL varchar(8),
NU_INTEGRALIZACAO_EAD varchar(8),
IN_OFERECE_DISC_SEMI_PRES varchar(8),
NU_PERC_CAR_HOR_SEMI_PRES varchar(8),
IN_POSSUI_LABORATORIO varchar(8),
QT_INSCRITOS_PRINCIPAL_EAD varchar(8),
QT_VAGAS_PRINCIPAL_EAD varchar(8),
QT_VAGAS_PRINCIPAL_INTEGRAL varchar(8),
QT_VAGAS_PRINCIPAL_MATUTINO varchar(8),
QT_VAGAS_PRINCIPAL_NOTURNO varchar(8),
QT_VAGAS_PRINCIPAL_VESPERTINO varchar(8),
QT_INSCRITOS_PRINCIPAL_MATU varchar(8),
QT_INSCRITOS_PRINCIPAL_VESP varchar(8),
QT_INSCRITOS_PRINCIPAL_NOTURNO varchar(8),
QT_INSCRITOS_PRINCIPAL_INTE varchar(8),
QT_INSCRITOS_OUTRAS_VAGAS_EAD varchar(8),
QT_OUTRAS_VAGAS_EAD varchar(8),
QT_OUTRAS_VAGAS_INTEGRAL varchar(8),
QT_OUTRAS_VAGAS_MATUTINO varchar(8),
QT_OUTRAS_VAGAS_NOTURNO varchar(8),
QT_OUTRAS_VAGAS_VESPERTINO varchar(8),
QT_INSCRITOS_OUTRAS_VAGAS_MATU varchar(8),
QT_INSCRITOS_OUTRAS_VAGAS_VESP varchar(8),
QT_INSCRITOS_OUTRAS_VAGAS_NOT varchar(8),
QT_INSCRITOS_OUTRAS_VAGAS_INTE varchar(8),
QT_MATRICULA_CURSO varchar(8),
QT_CONCLUINTE_CURSO varchar(8),
QT_INGRESSO_CURSO varchar(8),
QT_INGRESSO_PROCESSO_SELETIVO varchar(8)
);


load data local infile 'H:/HEDU/Dados/2013/Dados/DM_CURSO.csv'
into table IES_2013_CURSO
character set 'latin1'
fields terminated by '|'
lines terminated by '\n'
ignore 1 lines;

select * from IES_2013_CURSO;




