LOAD DATA LOCAL INFILE '/Users/r13/dev/projects/dataviva-etl/data/RAIS_2002/RAIS2002TOTAL.TXT' INTO TABLE RAIS2002TOTAL 
CHARACTER SET'ascii'
FIELDS TERMINATED BY '|' 
LINES TERMINATED BY '\n'
IGNORE 1 LINES;