CREATE TABLE BIBLIOTECA (
CO_UNIDADE_FUNCIONAMENTO numeric(8) NULL,
CO_BIBLIOTECA numeric(8) NULL,
CO_TIPO_BIBLIOTECA numeric(8) NULL,
IN_REDE_WIRELESS numeric(8) NULL,
IN_CATALOGO_ONLINE numeric(8) NULL,
QT_ASSENTO numeric(8) NULL,
QT_EMPRESTIMO_DOMICILIAR numeric(8) NULL,
QT_EMPRESTIMO_BIBLIOTECA numeric(8) NULL,
QT_COMUTACAO numeric(8) NULL,
QT_USUARIO_CAPACITADO numeric(8) NULL,
QT_ACERVO numeric(8) NULL
);