-- select DOCENTE SC 2009
use dataviva_raw;

-- Selecionando as variaveis
drop table if exists SC_2009_ESCOLA_STEP1;
create table SC_2009_ESCOLA_STEP1 
select PK_COD_ENTIDADE, DESC_SITUACAO_FUNCIONAMENTO, NUM_FUNCIONARIOS, ID_ALIMENTACAO, ID_EDUCACAO_INDIGENA
from SC_2009_ESCOLA;

drop table if exists SC_2009_DOCENTE_STEP1;
create table SC_2009_DOCENTE_STEP1 
select ANO_CENSO,FK_COD_DOCENTE,NUM_IDADE,TP_SEXO,TP_COR_RACA,FK_COD_MUNICIPIO_DEND,
	   FK_COD_ESCOLARIDADE,ID_ESPECIALIZACAO,ID_MESTRADO,ID_DOUTORADO,ID_POS_GRADUACAO_NENHUM,
       ID_TIPO_DOCENTE,FK_COD_MOD_ENSINO,FK_COD_ETAPA_ENSINO,FK_COD_CURSO_PROF,
       PK_COD_ENTIDADE,ID_DEPENDENCIA_ADM,PK_COD_AREA_OCDE_1, FK_COD_MUNICIPIO,
       ID_QUIMICA,ID_FISICA,ID_MATEMATICA,ID_BIOLOGIA,ID_CIENCIAS,ID_LINGUA_LITERAT_PORTUGUESA,
       ID_LINGUA_LITERAT_INGLES,ID_LINGUA_LITERAT_ESPANHOL,ID_LINGUA_LITERAT_OUTRA,ID_ARTES,
       ID_EDUCACAO_FISICA,ID_HISTORIA,ID_GEOGRAFIA,ID_FILOSOFIA,ID_ESTUDOS_SOCIAIS,
       ID_INFORMATICA_COMPUTACAO,ID_PROFISSIONALIZANTE,ID_DISC_ATENDIMENTO_ESPECIAIS,
       ID_DISC_DIVERSIDADE_SOCIO_CULT,ID_OUTRAS_DISCIPLINAS_PEDAG,ID_LIBRAS,ID_OUTRAS_DISCIPLINAS,
       ID_DIDATICA_METODOLOGIA,ID_FUNDAMENTOS_EDUCACAO
from SC_2009_DOCENTE;


# Criando o step 2:

drop table if exists SC_2009_DOCENTE_STEP2;
create table SC_2009_DOCENTE_STEP2 select * from SC_2009_DOCENTE_STEP1;

# Criando a variável com o nome da disciplina ofertada pelo docente:

alter table SC_2009_DOCENTE_STEP2 add DISCIPLINA int(2);


update SC_2009_DOCENTE_STEP2 set DISCIPLINA=
if(ID_QUIMICA=1,4,
if(ID_FISICA=1,5,
if(ID_MATEMATICA=1,6,
if(ID_BIOLOGIA=1,7,
if(ID_CIENCIAS=1,8,
if(ID_LINGUA_LITERAT_PORTUGUESA=1,9,
if(ID_LINGUA_LITERAT_INGLES=1,10,
if(ID_LINGUA_LITERAT_ESPANHOL=1,11,
if(ID_LINGUA_LITERAT_OUTRA=1,12,
if(ID_ARTES=1,13,
if(ID_EDUCACAO_FISICA=1,14,
if(ID_HISTORIA=1,15,
if(ID_GEOGRAFIA=1,16,
if(ID_FILOSOFIA=1,17,
if(ID_ESTUDOS_SOCIAIS=1,18,
if(ID_INFORMATICA_COMPUTACAO=1,19,
if(ID_PROFISSIONALIZANTE=1,20,
if(ID_DISC_ATENDIMENTO_ESPECIAIS=1,21,
if(ID_DISC_DIVERSIDADE_SOCIO_CULT=1,22,
if(ID_OUTRAS_DISCIPLINAS_PEDAG=1,23,
if(ID_LIBRAS=1,24,
if(ID_OUTRAS_DISCIPLINAS=1,25,
if(ID_DIDATICA_METODOLOGIA=1,26,
if(ID_FUNDAMENTOS_EDUCACAO=1,27,0))))))))))))))))))))))));


-- Unindo os bancos Docente e Escola:

ALTER TABLE SC_2009_DOCENTE_STEP2 DROP NUM_FUNCIONARIOS;
ALTER TABLE SC_2009_DOCENTE_STEP2 DROP DESC_SITUACAO_FUNCIONAMENTO;
ALTER TABLE SC_2009_DOCENTE_STEP2 DROP ID_ALIMENTACAO;
ALTER TABLE SC_2009_DOCENTE_STEP2 DROP ID_EDUCACAO_INDIGENA;

alter table SC_2009_DOCENTE_STEP2 add (
DESC_SITUACAO_FUNCIONAMENTO varchar(8), 
NUM_FUNCIONARIOS varchar(8), 
ID_ALIMENTACAO varchar(8), 
ID_EDUCACAO_INDIGENA varchar(8));


--  NUMERO DE FUNCIONÁRIOS

update SC_2009_DOCENTE_STEP2 left join SC_2009_ESCOLA_STEP1 
on SC_2009_DOCENTE_STEP2.PK_COD_ENTIDADE = SC_2009_ESCOLA_STEP1.PK_COD_ENTIDADE
set SC_2009_DOCENTE_STEP2.NUM_FUNCIONARIOS = SC_2009_ESCOLA_STEP1.NUM_FUNCIONARIOS;

update SC_2009_DOCENTE_STEP2 left join SC_2009_ESCOLA_STEP1 
on SC_2009_DOCENTE_STEP2.PK_COD_ENTIDADE = SC_2009_ESCOLA_STEP1.PK_COD_ENTIDADE
set SC_2009_DOCENTE_STEP2.ID_ALIMENTACAO = SC_2009_ESCOLA_STEP1.ID_ALIMENTACAO;

update SC_2009_DOCENTE_STEP2 left join SC_2009_ESCOLA_STEP1 
on SC_2009_DOCENTE_STEP2.PK_COD_ENTIDADE = SC_2009_ESCOLA_STEP1.PK_COD_ENTIDADE
set SC_2009_DOCENTE_STEP2.ID_EDUCACAO_INDIGENA = SC_2009_ESCOLA_STEP1.ID_EDUCACAO_INDIGENA;





SELECT NUM_FUNCIONARIOS,count(*) FROM SC_2009_ESCOLA_STEP1 group by NUM_FUNCIONARIOS;




select DISCIPLINA, count(*) from SC_2009_DOCENTE_STEP2 group by DISCIPLINA;



select ID_QUIMICA, count(*) from SC_2009_DOCENTE_STEP2 group by ID_QUIMICA;


select count(*) from SC_2009_DOCENTE_STEP2; 

select * from SC_2009_DOCENTE_STEP2;

select * from SC_2009_DOCENTE where  FK_COD_DOCENTE='   115002358577';

select * from SC_2009_DOCENTE; 

