from helpers import read_from_csv

''' Transform

Join sum in one field
'''
def transform(year):

    colsCurso = ('CO_IES', 'CO_CATEGORIA_ADMINISTRATIVA', 'CO_ORGANIZACAO_ACADEMICA', 'CO_NIVEL_ACADEMICO', 'CO_MODALIDADE_ENSINO', 'CO_GRAU_ACADEMICO', 'CO_CURSO', 'NO_CURSO', 'CO_MUNICIPIO_CURSO', 'CO_OCDE_AREA_GERAL', 'NO_OCDE_AREA_GERAL', 'CO_OCDE_AREA_ESPECIFICA', 'NO_OCDE_AREA_ESPECIFICA', 'CO_OCDE_AREA_DETALHADA', 'NO_OCDE_AREA_DETALHADA', 'CO_OCDE', 'NO_OCDE', 'IN_MATUTINO_CURSO', 'IN_VESPERTINO_CURSO', 'IN_NOTURNO_CURSO', 'IN_INTEGRAL_CURSO', 'QT_MATRICULA_CURSO', 'QT_CONCLUINTE_CURSO', 'QT_VAGAS_INTEGRAL_PRES', 'QT_VAGAS_MATUTINO_PRES', 'QT_VAGAS_NOTURNO_PRES', 'QT_VAGAS_VESPERTINO_PRES', 'QT_VAGAS_ANUAL_EAD')

    source_file = 'dados/importacao/sent/' + str(year) + str('_extract.csv')

    print source_file

    df = read_from_csv(source_file, 1, None, cols, None)

    if year == 2009:

        df['QT_VAGAS_CURSO'] = df['QT_VAGAS_INTEGRAL'] + df['QT_VAGAS_MATUTINO'] + df['QT_VAGAS_NOTURNO'] + df['QT_VAGAS_VESPERTINO']

        df.drop('QT_VAGAS_INTEGRAL', 'QT_VAGAS_MATUTINO', 'QT_VAGAS_NOTURNO', 'QT_VAGAS_VESPERTINO', 1)

    elif year > 2009:

        df['QT_VAGAS_CURSO'] = df['QT_VAGAS_INTEGRAL_PRES'] + df['QT_VAGAS_MATUTINO_PRES'] + df['QT_VAGAS_NOTURNO_PRES'] + df['QT_VAGAS_VESPERTINO_PRES'] + df['QT_VAGAS_ANUAL_EAD']

        df.drop('QT_VAGAS_INTEGRAL_PRES', 'QT_VAGAS_MATUTINO_PRES', 'QT_VAGAS_NOTURNO_PRES', 'QT_VAGAS_VESPERTINO_PRES', 'QT_VAGAS_ANUAL_EAD', 1)

    print df

if __name__ == "__main__":
    transform(2011)

