CREATE TABLE leitos_2010(
id int(11),
cnes varchar(7), 
codufmun varchar(6), 
regsaude varchar(4), 
micr_reg varchar(6),
distrsan varchar(4),
distradm varchar(4),
tpgestao varchar(1),
pf_pj varchar(1),
cpf_cnpj varchar(14),
niv_dep varchar(1),
cnpj_man varchar(14),
esfera_a varchar(2),
atividad varchar(2),
retencao varchar(2),
natureza varchar(2),
clientel varchar(2),
tp_unid varchar(2),
turno_at varchar(2),
niv_hier varchar(2), 
teceiro varchar (1), 
tp_leito varchar(2), 
codleito varchar(2), 
qt_exist double(4,0), 
qt_contr double(4,0),
qt_sus double(4,0), 
qt_nsus double(4,0),
competen varchar(6)
);