CREATE TABLE `dataviva_client`.`stat_ybi`(
    `year` varchar(4),
    `bra_id` varchar(9),
    `cnae_id` varchar(6),
    `wage` float,
    `num_jobs` int(9),
    `num_est` int(9),
    `wage_avg` float(18,2),
    `rca` float(18,2),
    `distance` float(18,2),
    `opp_gain` float(18,2));

CREATE TABLE `dataviva_client`.`stat_ybsc` (
  `year` YEAR NOT NULL COMMENT '',
  `bra_id` VARCHAR(11) NULL COMMENT '',
  `course_sc_id` VARCHAR(9) NULL COMMENT '',
  `enrollments` INT(10) NULL COMMENT '',
  `classes` INT(10) NULL COMMENT '',
  `total_school` INT(9) NULL COMMENT '',
  `average_class_size` DECIMAL(8,3) NULL COMMENT '',
  `average_age` DECIMAL(8,3) NULL COMMENT '',
  `top_school_enrollments` INT(11) NULL COMMENT '',
  `school_enrollments` INT(10) NULL COMMENT '',
  `top_municipality_enrollments` VARCHAR(11) NULL COMMENT '',
  `municipality_enrollments` INT(10) NULL COMMENT '');

CREATE TABLE `dataviva_client`.`stat_ybhedu` (
  `year` YEAR NOT NULL COMMENT '',
  `bra_id` VARCHAR(11) NULL COMMENT '',
  `course_hedu_id` VARCHAR(9) NULL COMMENT '',
  `enrollments` INT(11) NULL COMMENT '',
  `entrants` INT(11) NULL COMMENT '',
  `graduates` INT(11) NULL COMMENT '',
  `top_university_enrollments` VARCHAR(8) NULL COMMENT '',
  `university_enrollments` INT(10) NULL COMMENT '',
  `top_municipality_enrollments` VARCHAR(11) NULL COMMENT '',
  `municipality_enrollments` INT(10) NULL COMMENT '',
  `top_university_entrants` VARCHAR(8) NULL COMMENT '',
  `university_entrants` INT(10) NULL COMMENT '',
  `top_municipality_entrants` VARCHAR(11) NULL COMMENT '',
  `municipality_entrants` INT(10) NULL COMMENT '',
  `top_university_graduates` VARCHAR(8) NULL COMMENT '',
  `university_graduates` INT(10) NULL COMMENT '',
  `top_municipality_graduates` VARCHAR(11) NULL COMMENT '',
  `municipality_graduates` INT(10) NULL COMMENT '');

CREATE TABLE `dataviva_client`.`stat_ybu` (
  `year` YEAR NOT NULL COMMENT '',
  `bra_id` VARCHAR(11) NULL COMMENT '',
  `university_id` VARCHAR(9) NULL COMMENT '',
  `enrollments` INT(10) NULL COMMENT '',
  `entrants` INT(10) NULL COMMENT '',
  `graduates` INT(10) NULL COMMENT '',
  `top_course_enrollments` VARCHAR(9) NULL COMMENT '',
  `course_enrollments` INT(10) NULL COMMENT '',
  `top_course_entrants` VARCHAR(9) NULL COMMENT '',
  `course_entrants` INT(10) NULL COMMENT '',
  `top_course_graduates` VARCHAR(9) NULL COMMENT '',
  `course_graduates` INT(10) NULL COMMENT '');

CREATE TABLE `dataviva_client`.`stat_ybhs` (
  `year` YEAR NOT NULL COMMENT '',
  `bra_id` VARCHAR(11) NULL COMMENT '',
  `hs_id` VARCHAR(9) NULL COMMENT '',
  `trade_balance` BIGINT NULL COMMENT '',
  `export_val` BIGINT COMMENT '',
  `weight_value_export` DOUBLE NULL COMMENT '',
  `import_val` BIGINT NULL COMMENT '',
  `weight_value_import` DOUBLE NULL COMMENT '',
  `pci` DOUBLE NULL COMMENT '',
  `rca` DOUBLE NULL COMMENT '',
  `distance` DOUBLE NULL COMMENT '',
  `opp_gain` DOUBLE NULL COMMENT '',
  `top_municipality_export` VARCHAR(45) NULL COMMENT '',
  `municipality_export` BIGINT NULL COMMENT '',
  `top_municipality_import` VARCHAR(45) NULL COMMENT '',
  `municipality_import` BIGINT NULL COMMENT '',
  `top_export_destiny` VARCHAR(7) NULL COMMENT '',
  `top_export_value` BIGINT NULL COMMENT '',
  `top_import_origin` VARCHAR(7) NULL COMMENT '',
  `top_import_value` BIGINT NULL COMMENT '');

 CREATE TABLE `dataviva_client`.`stat_ybtrade_partner` (
  `year` YEAR NOT NULL COMMENT '',
  `wld_id` VARCHAR(11) NULL COMMENT '',
  `trade_balance` BIGINT NULL COMMENT '',
  `export_val` BIGINT COMMENT '',
  `weight_value_export` DOUBLE NULL COMMENT '',
  `import_val` BIGINT NULL COMMENT '',
  `weight_value_import` DOUBLE NULL COMMENT '',
  `top_municipality_export` VARCHAR(45) NULL COMMENT '',
  `municipality_export` BIGINT NULL COMMENT '',
  `top_municipality_import` VARCHAR(45) NULL COMMENT '',
  `municipality_import` BIGINT NULL COMMENT '',
  `top_export_product` VARCHAR(7) NULL COMMENT '',
  `top_export_product_value` BIGINT NULL COMMENT '',
  `top_import_product` VARCHAR(7) NULL COMMENT '',
  `top_import_product_value` BIGINT NULL COMMENT '',
  `product_higher_trade_balance` VARCHAR(7) NULL COMMENT '',
  `product_higher_value` BIGINT NULL COMMENT '',
  `product_lower_trade_balance` VARCHAR(7) NULL COMMENT '',
  `product_lower_value` BIGINT NULL COMMENT '');