CREATE TABLE equi_2014(
id int(11),
cnes varchar(7),
codufmun varchar(6), 
regsaude varchar(4), 
micr_reg varchar(20), 
distrsan varchar (10), 
distradm varchar(4), 
tpgestao varchar(1), 
pf_pj varchar(1),
cpf_cnpj varchar(14), 
niv_dep varchar(1), 
cnpj_man varchar(14), 
esfera_a varchar(2), 
atividad varchar(2), 
retencao varchar(2),
natureza varchar(2),
clientel varchar(2), 
tp_unid varchar(2), 
turno_at varchar(2),
niv_hier varchar(2), 
terceiro varchar(1),
tipequip varchar(1),
codequip varchar(2), 
qt_exist double(4,0), 
qt_uso double(4,0), 
ind_sus varchar(1), 
ind_nsus varchar(1), 
competen varchar(6)
);