DELIMITER $$
CREATE PROCEDURE ROWPERROW()
BEGIN
    DECLARE n INT DEFAULT 0;
    DECLARE i INT DEFAULT 0;
    SELECT COUNT(*) FROM RAIS2003 INTO n;
    SET i=0;
    WHILE i<n DO 
        INSERT INTO RAIS2003_Selecao SELECT PIS, RADIC_CNPJ, MUNICIPIO, SEXO, IDADE, RACA_COR, GRAU_INSTR_FONTE,
		REM_MEDIA_RS, CBO_2002, CLAS_CNAE_95, TAM_ESTAB_FONTE, IND_SIMPLES_FONTE, NATUR_JUR_FONTE
        FROM RAIS2003 LIMIT i, 60000;
        SET i = i + 60000;
    END WHILE;
END $$
DELIMITER ;

