DELIMITER $$
CREATE PROCEDURE ROWPERROW()
BEGIN
    DECLARE n INT DEFAULT 0;
    DECLARE i INT DEFAULT 0;
    SELECT COUNT(*) FROM RAIS2003 INTO n;
    SET i=0;
    WHILE i<n DO 
        INSERT INTO RAIS2003_Selecao SELECT PIS, RADIC_CNPJ, MUNICIPIO, SEXO, IDADE, RACA_COR, GRAU_INSTR_FONTE,
		REM_MEDIA_RS, CBO_2002, CLAS_CNAE_95, TAM_ESTAB_FONTE, IND_SIMPLES_FONTE, NATUR_JUR_FONTE
        FROM RAIS2003 LIMIT i, 60000;
        SET i = i + 60000;
    END WHILE;
END $$
DELIMITER ;



-- Teste


ALTER TABLE rais2003 
DROP COLUMN CAUSA_DESLI,
DROP COLUMN CAUSA_DESLI_FONTE,
DROP COLUMN CBO_2002_FONTE,
DROP COLUMN CEI_VINC,
DROP COLUMN CLAS_CNAE_95_FONTE,
DROP COLUMN EMP_31_12,
DROP COLUMN EMP_31_12_FONTE,
DROP COLUMN GRAU_INSTR,
DROP COLUMN HORAS_CONTR,	
DROP COLUMN IDENTIFICAD,
DROP COLUMN IND_CEI_VINC,
DROP COLUMN IND_CEI_VINC_FONTE,
DROP COLUMN IND_PAT,
DROP COLUMN IND_PAT_FONTE,
DROP COLUMN IND_SIMPLES,
DROP COLUMN MUNICIPIO_FONTE,
DROP COLUMN NACIONALIDADE,
DROP COLUMN NACIONALIDADE_FONTE,
DROP COLUMN NATUR_JUR,	
DROP COLUMN RACA_COR_FONTE,
DROP COLUMN REM_DEZ_RS,
DROP COLUMN REM_DEZEMBRO,
DROP COLUMN REM_MEDIA,
DROP COLUMN SUBS_IBGE,
DROP COLUMN SEXO_FONTE,
DROP COLUMN TAM_ESTAB,
DROP COLUMN TEMP_EMPR,
DROP COLUMN TIPO_ADM,
DROP COLUMN TIPO_ADM_FONTE,
DROP COLUMN TIPO_ESTAB,
DROP COLUMN TIPO_ESTAB_FONTE,
DROP COLUMN TP_VINCULO,
DROP COLUMN TP_VINCULO_FONrais2003TE,
DROP COLUMN DT_NASCIMENT,
DROP COLUMN DT_ADMISSAO,
DROP COLUMN MES_DESLIG,
DROP COLUMN MES_DESLIG_FONTE  
;

