CREATE TABLE RAIS_2002(
    CAUSA_DESLI varchar(50),
    CAUSA_DESLI_Fonte varchar(50),
    OCUPACAO varchar(50),
    OCUPACAO_Desc varchar(50),
    IND_CEI_VINC varchar(50),
    CLAS_CNAE_95 varchar(50),
    CLAS_CNAE_95_Fonte varchar(50),
    GRAU_INSTR varchar(50),
    GRAU_INSTR_Fonte varchar(50),
    HORAS_CONTR varchar(50),
    IDADE varchar(50),
    IDENTIFICAD varchar(50) ,
    IND_PAT varchar(50) ,
    IND_PAT_Fonte varchar(50) ,
    IND_SIMPLES varchar(50) ,
    IND_SIMPLES_Fonte varchar(50) ,
    MUNICIPIO varchar(50) ,
    MUNICIPIO_Fonte varchar(50) ,
    NACIONALIDAD varchar(50) ,
    NACIONALIDAD_Fonte varchar(50) ,
    NATUR_JUR varchar(50) ,
    NATUR_JUR_Fonte varchar(50) ,
    PIS varchar(50) ,
    RACA_COR_OR varchar(50) ,
    RACA_COR_OR_Fonte varchar(50) ,
    RADIC_CNPJ varchar(50) ,
    REM_DEZ varchar(50) ,
    REM_DEZEMBRO varchar(50) ,
    REM_MED  varchar(50) ,
    SUBS_IBGE varchar(50) ,
    SEXO_varchar varchar(50) ,
    SEXO_Fonte varchar(50) ,
    TAMESTAB varchar(50) ,
    TAMESTAB_Fonte varchar(50) ,
    TEMP_EMPR varchar(50) ,
    TIPO_ADM varchar(50) ,
    TIPO_ADM_Fonte varchar(50) ,
    TIPO_ESTBL varchar(50) ,
    TIPO_ESTBL_Fonte varchar(50) ,
    TP_VINCL varchar(50) ,
    DT_NASCIMENT varchar(50) ,
    MES_DESLIG varchar(50) ,
    MES_DESLIG_Fonte varchar(50) ,
    DT_ADMISSAO varchar(50)
);